### PR TITLE
Added send verification feedback

### PR DESCRIPTION
**Pull request by silentrald**

### CODE REVIEW

**Comment by silentrald** [comment]
[[US#26C] Verification email link undefined](https://trello.com/c/tdzzTCpl/91-us26c-verification-email-link-undefined)

**Comment by silentrald** [comment]
[[US#26A] No feedback on the website whether e-mail was sent](https://trello.com/c/gIXY1z8W/82-us26a-no-feedback-on-the-website-whether-e-mail-was-sent)

**Comment by silentrald** [comment]
[[US#31A] 'Verify Account' visible when viewing profile of a different user](https://trello.com/c/l5leuIa3/87-us31a-verify-account-visible-when-viewing-profile-of-a-different-user)

**Review by S0rbetes — APPROVED** [review]

**Comment by S0rbetes** [comment]
[[US#31B] 'Verify Account' Button is still visible in profile page after verification](https://trello.com/c/pKv43cpr/89-us31b-verify-account-button-is-still-visible-in-profile-page-after-verification)

**Pull request merged**
